name: CI

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      submodules: true
    - name: build
      run: |
        sed -i 's/ -it / /' build.sh
        ./build.sh
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: |
          ./build/
          ./dist/
